### ISSUE TITLE
Tx fail

### ISSUE THREAD

**Issue by elpinyeknom** [dawn-network/glogchain#14]
//Tx-fail

https://drive.google.com/file/d/0B7wsOGnypJbdcXZqVWVZc1hpLVE/view?usp=sharing

**Comment by baabeetaa** [comment]
just test again in local, works! Need to check the log to know what is the problem.

![screen shot 2017-02-13 at 8 11 42 pm](https://cloud.githubusercontent.com/assets/11970690/22884664/afb4921a-f228-11e6-96eb-37532b5c866c.png)

**Comment by elpinyeknom** [comment]
Try 96.9.90.100:8000

**Comment by faddat** [comment]
Teaching Forrest SSH now, he will login to the router and retrieve the logs :).

**Comment by faddat** [comment]
Fixed in new release by @baabeetaa
